name: chat_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: 2.0.17
  freezed: ^2.5.8
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.11
  toastification: ^2.3.0
  faker: ^2.2.0
  shimmer: ^3.0.0
  custom_refresh_indicator: ^4.0.1
  pull_to_refresh: ^2.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  provider: ^6.1.4
  go_router: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:  


flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/illustrations/

